package com.zsc.game.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zsc.game.greendao.Data;
import com.zsc.game.greendao.LoadInfo;
import com.zsc.game.greendao.Mls;

import com.zsc.game.greendao.DataDao;
import com.zsc.game.greendao.LoadInfoDao;
import com.zsc.game.greendao.MlsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dataDaoConfig;
    private final DaoConfig loadInfoDaoConfig;
    private final DaoConfig mlsDaoConfig;

    private final DataDao dataDao;
    private final LoadInfoDao loadInfoDao;
    private final MlsDao mlsDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dataDaoConfig = daoConfigMap.get(DataDao.class).clone();
        dataDaoConfig.initIdentityScope(type);

        loadInfoDaoConfig = daoConfigMap.get(LoadInfoDao.class).clone();
        loadInfoDaoConfig.initIdentityScope(type);

        mlsDaoConfig = daoConfigMap.get(MlsDao.class).clone();
        mlsDaoConfig.initIdentityScope(type);

        dataDao = new DataDao(dataDaoConfig, this);
        loadInfoDao = new LoadInfoDao(loadInfoDaoConfig, this);
        mlsDao = new MlsDao(mlsDaoConfig, this);

        registerDao(Data.class, dataDao);
        registerDao(LoadInfo.class, loadInfoDao);
        registerDao(Mls.class, mlsDao);
    }
    
    public void clear() {
        dataDaoConfig.clearIdentityScope();
        loadInfoDaoConfig.clearIdentityScope();
        mlsDaoConfig.clearIdentityScope();
    }

    public DataDao getDataDao() {
        return dataDao;
    }

    public LoadInfoDao getLoadInfoDao() {
        return loadInfoDao;
    }

    public MlsDao getMlsDao() {
        return mlsDao;
    }

}
