package com.zsc.game.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MLS".
*/
public class MlsDao extends AbstractDao<Mls, Long> {

    public static final String TABLENAME = "MLS";

    /**
     * Properties of entity Mls.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Vid = new Property(1, String.class, "vid", false, "VID");
        public final static Property Titile = new Property(2, String.class, "titile", false, "TITILE");
        public final static Property Json = new Property(3, String.class, "json", false, "JSON");
    }


    public MlsDao(DaoConfig config) {
        super(config);
    }
    
    public MlsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MLS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"VID\" TEXT," + // 1: vid
                "\"TITILE\" TEXT," + // 2: titile
                "\"JSON\" TEXT);"); // 3: json
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MLS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Mls entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String vid = entity.getVid();
        if (vid != null) {
            stmt.bindString(2, vid);
        }
 
        String titile = entity.getTitile();
        if (titile != null) {
            stmt.bindString(3, titile);
        }
 
        String json = entity.getJson();
        if (json != null) {
            stmt.bindString(4, json);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Mls entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String vid = entity.getVid();
        if (vid != null) {
            stmt.bindString(2, vid);
        }
 
        String titile = entity.getTitile();
        if (titile != null) {
            stmt.bindString(3, titile);
        }
 
        String json = entity.getJson();
        if (json != null) {
            stmt.bindString(4, json);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Mls readEntity(Cursor cursor, int offset) {
        Mls entity = new Mls( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // vid
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // titile
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // json
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Mls entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setVid(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTitile(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setJson(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Mls entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Mls entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Mls entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
